### ISSUE TITLE
Rota para get Usuário pelo ID

### ISSUE THREAD

**Issue by pedrordgsr** [Dankei/Setec-o-Y#36]
Preciso de uma rota
router.get('/users/getByID/:id', userController.findByID)
para encontrar um usuário pelo ID
não precisa necessariamente ser nesse url

![image](https://github.com/user-attachments/assets/ac9281cc-518d-4ec2-99ea-31f11c150c0c)
minha intenção com essa rota é pegar o authorID do yeet e mostrar o nome do usuario correto

**Comment by Dankei** [comment]
Feito adição de rota solicitada no pr 37
